### PR TITLE
[WIP] Arguments and CLI help text

### LINKED ISSUE #7: Argument names and short versions
## Current output

The current `treedoc --help` output is:

```text
usage: treedoc [-h] [--level [LEVEL]] [--subpackages] [--modules] [--private]
               [--magic] [--tests] [--printer [{simple,dense}]]
               [--signature {0,1,2}] [--docstring {0,1,2,3,4}]
               [--info {0,1,2,3,4}]
               [obj]

Minimalistic documentation in a tree structure.

positional arguments:
  obj                   The object

optional arguments:
  -h, --help            show this help message and exit

traversal:
  The arguments are common to every printer.

  --level [LEVEL]       descend only level directories deep.
  --subpackages         descend into subpackages, i.e. numpy -> numpy.linalg
  --modules             descend into every module in a package.
  --private             show private objects, i.e. _func(x).
  --magic               show magic methods, i.e. __add(self, other)__.
  --tests               show tests, i.e. test_func().

printing:
  The meaning of the arguments varies depending on the printer.

  --printer [{simple,dense}]
                        printer to use, defaults to 'simple'
  --signature {0,1,2}   how much signature information to show.
  --docstring {0,1,2,3,4}
                        how much docstring information to show.
  --info {0,1,2,3,4}    how much general information to show.

Report issues and contribute on https://github.com/tommyod/treedoc.

```

## Discussion points

I would like to:
1. Land a good, descriptive tagline for the project. The current one is "Minimalistic documentation in a tree structure."
2. Have good names for the arguments in general. They must be standard names as well as descriptive.
3. Ideally have arguments with unique first characters, so that we can have `-m` as an alias for `--modules`. Currently some argument names clash, i.e. `--signature` and `--subpackages`. We can
   1. rename them
   2. use capital letters for one of them, i.e. `-s` short for `--signature` and `-S` short for `--subpackages`
   3. shorten them to e.g. `-sig` short for `--signature` and `-sub` short for `--subpackages`

## Thoughts

- obj: can be called "obj" or "object".
- level: the linux command `tree` calls this "level", and uses `-L`. The linux command `find` has the argument `-maxdepth`, and uses the wording `Descend at most levels...` in the man page. In the literature on trees the word "depth" is more commonly used.
- subpackages: could also be called "packages", but "subpackages" is more descriptive.
- modules: a module is just a python file, so it could be called "files". but "module" is the proper word in my opinion.
- private: not many options here. 
- magic: these methods are commonly called "dunder methods" or "magic methods". in the [official docs](https://docs.python.org/3/reference/datamodel.html) they called called "special attributes". 
- tests: simple filter for objects whose names start with "test". Seems like a reasonable name.
- printer: the type of printer to use. could be called "output" or something similar too. The classes are called "printers" in the source code. They could've been called "printers", "formatters", "outputters", etc.
- signature: in the `inspect` built in module, the terms "arg spec" and "signature" are both used. Signature is clearer in my opinion.
- docstring: Not much to say about this. Could've been called "docs" og "documentation", but the "docstring" is specifically the string under the definition, while "documentation" is more general.
- info: general level of information. This can be called "detail", "information", "verbosity", etc too.

------

I'm opening this Issue to think about this. If we can settle the terminology early on we won't have too many iterations with rewording. Do you have any thoughts @smu095 ?

### PR DESCRIPTION
**Pull request by tommyod**
- [ ] Decide on a project tagline.
- [ ] Decide on CLI argument names.
- [ ] Decide on CLI help screen, i.e. `treedoc --help` output.

This PR closes #7

### CODE REVIEW

**Comment by tommyod** [comment]
Here's the best I can come up with:

```
usage: treedoc [-h] [-d [DEPTH]] [-s] [-mod] [-p] [-m] [-t]
               [--printer [{tree,dense}]] [-sig {0,1,2}] [-doc {0,1,2,3,4}]
               [-i {0,1,2,3,4}]
               [object]

Minimalistic Python documentation in a tree structure.

positional arguments:
  object                package/class/method/... , e.g. collections.Counter

optional arguments:
  -h, --help            show this help message and exit

traversal:
  The arguments below are common to every printer.

  -d [DEPTH], --depth [DEPTH]
                        descend no more than DEPTH levels in the object tree.
  -s, --subpackages     descend into subpackages, e.g. numpy -> numpy.linalg
  -mod, --modules       descend into every module in a package.
  -p, --private         show private objects, e.g. _func(x).
  -m, --magic           show magic methods, e.g. __add(self, other)__.
  -t, --tests           show tests, e.g. test_func().

printing:
  The meaning of the arguments below may vary depending on the printer.
  Numeric arguments default to middle values, printer defaults to 'tree'.

  --printer [{tree,dense}]
                        general output formatting style.
  -sig {0,1,2}, --signature {0,1,2}
                        how much signature information to show.
  -doc {0,1,2,3,4}, --docstring {0,1,2,3,4}
                        how much docstring information to show.
  -i {0,1,2,3,4}, --info {0,1,2,3,4}
                        how much general information to show.

Report issues and contribute on https://github.com/tommyod/treedoc.
```

Any thoughts on this @smu095 ?

**Comment by tommyod** [comment]
Added a nice feature: running `treedoc python` will import every package on the system in turn and run `treedoc` on it. Currently it fails on my system, as treedoc is not robust enough yet.

**Comment by glemvik** [comment]
I think it looks intuitive and easy to use as it is, but I have two thoughts after comparing it to 'tree --help':

1. In 'tree --help' they use -L to specify the level of directories to descend. I think I prefer -d (and I see that you have replaced 'level' by 'depth' already), but I thought this difference was worth mentioning since treedoc was (correct me if I'm wrong) inspired by tree.

2. In 'tree --help' any argument that is longer than one letter is preceded by two dashes, and not all such arguments have a corresponding single-dash short argument. For two arguments with the same first letter, one is given a lowercase single-dash short argument, and the other is given a capital single-dash short argument. Below, you find two proposals following this convention.

Proposal 1:
```
[...]
optional arguments:
  -h, --help            show this help message and exit

traversal:
  The arguments below are common to every printer.

  -d [DEPTH], --depth [DEPTH]
                        descend no more than DEPTH levels in the object tree.
  -s, --subpackages     descend into subpackages, e.g. numpy -> numpy.linalg
  -m, --modules         descend into every module in a package.
  -p, --private         show private objects, e.g. _func(x).
  -M, --magic           show magic methods, e.g. __add(self, other)__.
  -t, --tests           show tests, e.g. test_func().

printing:
  The meaning of the arguments below may vary depending on the printer.
  Numeric arguments default to middle values, printer defaults to 'tree'.

  -P, --printer [{tree,dense}]
                        general output formatting style.
  -S {0,1,2}, --signature {0,1,2}
                        how much signature information to show.
  -D {0,1,2,3,4}, --docstring {0,1,2,3,4}
                        how much docstring information to show.
  -i {0,1,2,3,4}, --info {0,1,2,3,4}
                        how much general information to show.
[...]
```

Proposal 2:
```
[...]
optional arguments:
  -h, --help            show this help message and exit

traversal:
  The arguments below are common to every printer.

  -d [DEPTH], --depth [DEPTH]
                        descend no more than DEPTH levels in the object tree.
  -s, --subpackages     descend into subpackages, e.g. numpy -> numpy.linalg
  -m, --modules         descend into every module in a package.
  -p, --private         show private objects, e.g. _func(x).
  -M, --magic           show magic methods, e.g. __add(self, other)__.
  -t, --tests           show tests, e.g. test_func().

printing:
  The meaning of the arguments below may vary depending on the printer.
  Numeric arguments default to middle values, printer defaults to 'tree'.

  --printer [{tree,dense}]
                        general output formatting style.
  --signature {0,1,2}
                        how much signature information to show.
  --docstring {0,1,2,3,4}
                        how much docstring information to show.
  --info {0,1,2,3,4}
                        how much general information to show.
[...]
```

**Comment by tommyod** [comment]
Here's my latest proposal:

```
usage: treedoc [-h] [-l [LEVELS]] [-s] [-m] [-p] [-d] [-t] [-P [{tree,dense}]] [-S {0,1,2}] [-D {0,1,2,3,4}] [-I {0,1,2,3,4}] [object]

Minimalistic Python documentation in a tree structure.

positional arguments:
  object                package/class/method/... , e.g. collections.Counter

optional arguments:
  -h, --help            show this help message and exit

traversal:
  The arguments below are common to every printer.

  -l [LEVELS], --levels [LEVELS]
                        descend no more than LEVELS in the object tree.
  -s, --subpackages     descend into subpackages, e.g. numpy -> numpy.linalg
  -m, --modules         descend into every module in a package.
  -p, --private         show private objects, e.g. _func(x).
  -d, --dunders         show double underscore methods, e.g. __add(self, other)__.
  -t, --tests           show tests, e.g. test_func().

printing:
  The meaning of the arguments below may vary depending on the printer.
  Numeric arguments default to middle values, printer defaults to 'tree'.

  -P [{tree,dense}], --printer [{tree,dense}]
                        general output formatting style.
  -S {0,1,2}, --signature {0,1,2}
                        how much signature information to show.
  -D {0,1,2,3,4}, --docstring {0,1,2,3,4}
                        how much docstring information to show.
  -I {0,1,2,3,4}, --info {0,1,2,3,4}
                        how much general information to show.

Report issues and contribute on https://github.com/tommyod/treedoc.
```

**Advantages:** Every argument name has a one-character alias. Consistent interface with traversal options using lowercase and printing options using uppercase.

**Disadvtantages:** I would've preferred to use `depth` instead of `levels` and `magic` instead of `dunders`.

Thoughts on this proposal @smu095 @glemvik ? It's not perfect, but if you agree that it's probably as got as it's going to get I will implement it.

**Comment by glemvik** [comment]
I think it looks more clean than the initial proposal, and that changing the argument names is worth it

**Comment by tommyod** [comment]
Abandoning this PR in favor of #18

**Pull request closed without merging**
